//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnseremCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleId { get; set; }
        public string SaleName { get; set; }
        public Nullable<int> CounterpartyId { get; set; }
        public Nullable<int> ContactId { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual Counterparties Counterparties { get; set; }
    }
}
